name: "Lint"

on: [push, pull_request]

defaults:
  run:
    working-directory: server

jobs:

  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install black~=23.0
    - run: black --diff .

  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install flake8
    - run: flake8

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - run: pip install -Ur mypy-requirements.txt
    - run: mypy .
